spring.application.name=keycloak-sso-app
spring.profiles.active=dev
server.port=8080

spring.thymeleaf.cache=false

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.org.springframework.security=DEBUG
logging.level.com.orbit.sso=DEBUG