spring.security.oauth2.client.registration.keycloak.client-id=sso-app
spring.security.oauth2.client.registration.keycloak.client-secret=ZjoAtEkhmHie2yJf6FPQhj5QEokqsra2
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email,roles

spring.security.oauth2.client.registration.keycloak.redirect-uri=${APP_BASE_URL:http://localhost:8080}/login/oauth2/code/keycloak

spring.security.oauth2.client.provider.keycloak.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/sso-realm}
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username